namespace NesUnity
{
    using static AddressingMode;
    public partial class Cpu
    {
        private void InitInstructions()
        {
            Op("JSR", 0x20, JSR, Absolute,   6);
            Op("RTI", 0x40, RTI, Implicit,   6);
            Op("RTS", 0x60, RTS, Implicit,   6);
            Op("INY", 0xC8, INY, Implicit,   2);
            Op("DEY", 0x88, DEY, Implicit,   2);
            Op("INX", 0xE8, INX, Implicit,   2);
            Op("DEX", 0xCA, DEX, Implicit,   2, rmw: true);
            Op("TAY", 0xA8, TAY, Implicit,   2);
            Op("TYA", 0x98, TYA, Implicit,   2);
            Op("TAX", 0xAA, TAX, Implicit,   2, rmw: true);
            Op("TXA", 0x8A, TXA, Implicit,   2, rmw: true);
            Op("TSX", 0xBA, TSX, Implicit,   2);
            Op("TXS", 0x9A, TXS, Implicit,   2, rmw: true);
            Op("PHP", 0x08, PHP, Implicit,   3);
            Op("PLP", 0x28, PLP, Implicit,   4);
            Op("PLA", 0x68, PLA, Implicit,   4);
            Op("PHA", 0x48, PHA, Implicit,   3);
            Op("BIT", 0x24, BIT, ZeroPage,   3);
            Op("BIT", 0x2C, BIT, Absolute,   4);
            Op("JMP", 0x4C, JMP, Absolute,   3);
            Op("JMP", 0x6C, JMP, Indirect,   5);
            Op("BCS", 0xB0, BCS, Relative,   2);
            Op("BCC", 0x90, BCC, Relative,   2);
            Op("BEQ", 0xF0, BEQ, Relative,   2);
            Op("BNE", 0xD0, BNE, Relative,   2);
            Op("BVS", 0x70, BVS, Relative,   2);
            Op("BVC", 0x50, BVC, Relative,   2);
            Op("BPL", 0x10, BPL, Relative,   2);
            Op("BMI", 0x30, BMI, Relative,   2);
            Op("STA", 0x81, STA, IndirectX,  6);
            Op("STA", 0x91, STA, IndirectY,  6);
            Op("STA", 0x95, STA, ZeroPageX,  4);
            Op("STA", 0x99, STA, AbsoluteY,  5);
            Op("STA", 0x9D, STA, AbsoluteX,  5);
            Op("STA", 0x85, STA, ZeroPage,   3);
            Op("STA", 0x8D, STA, Absolute,   4);
            Op("STX", 0x96, STX, ZeroPageY,  4);
            Op("STX", 0x86, STX, ZeroPage,   3);
            Op("STX", 0x8E, STX, Absolute,   4);
            Op("STY", 0x94, STY, ZeroPageX,  4);
            Op("STY", 0x84, STY, ZeroPage,   3);
            Op("STY", 0x8C, STY, Absolute,   4);
            Op("CLC", 0x18, CLC, Implicit,   2);
            Op("SEC", 0x38, SEC, Implicit,   2);
            Op("CLI", 0x58, CLI, Implicit,   2);
            Op("SEI", 0x78, SEI, Implicit,   2);
            Op("CLV", 0xB8, CLV, Implicit,   2);
            Op("CLD", 0xD8, CLD, Implicit,   2);
            Op("SED", 0xF8, SED, Implicit,   2);
            Op("NOP", 0xEA, NOP, Implicit,   2);
            Op("NOP", 0x1A, NOP, Implicit,   2);
            Op("NOP", 0x3A, NOP, Implicit,   2);
            Op("NOP", 0x5A, NOP, Implicit,   2);
            Op("NOP", 0x7A, NOP, Implicit,   2);
            Op("NOP", 0xDA, NOP, Implicit,   2);
            Op("NOP", 0xFA, NOP, Implicit,   2);
            Op("NOP", 0x0C, NOP, Absolute,   4);
            Op("NOP", 0x1C, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("NOP", 0x3C, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("NOP", 0x5C, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("NOP", 0x7C, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("NOP", 0xDC, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("NOP", 0xFC, NOP, AbsoluteX,  4, pageBoundary: true);
            Op("LDA", 0xA1, LDA, IndirectX,  6);
            Op("LDA", 0xA5, LDA, ZeroPage,   3);
            Op("LDA", 0xA9, LDA, Immediate,  2);
            Op("LDA", 0xAD, LDA, Absolute,   4);
            Op("LDA", 0xB1, LDA, IndirectY,  5, pageBoundary: true);
            Op("LDA", 0xB5, LDA, ZeroPageX,  4);
            Op("LDA", 0xB9, LDA, AbsoluteY,  4, pageBoundary: true);
            Op("LDA", 0xBD, LDA, AbsoluteX,  4, pageBoundary: true);
            Op("LDY", 0xA0, LDY, Immediate,  2);
            Op("LDY", 0xA4, LDY, ZeroPage,   3);
            Op("LDY", 0xAC, LDY, Absolute,   4);
            Op("LDY", 0xB4, LDY, ZeroPageX,  4);
            Op("LDY", 0xBC, LDY, AbsoluteX,  4, pageBoundary: true);
            Op("LDX", 0xA2, LDX, Immediate,  2, rmw: true);
            Op("LDX", 0xA6, LDX, ZeroPage,   3, rmw: true);
            Op("LDX", 0xAE, LDX, Absolute,   4, rmw: true);
            Op("LDX", 0xB6, LDX, ZeroPageY,  4, rmw: true);
            Op("LDX", 0xBE, LDX, AbsoluteY,  4, true, true);
            Op("ORA", 0x01, ORA, IndirectX,  6);
            Op("ORA", 0x05, ORA, ZeroPage,   3);
            Op("ORA", 0x09, ORA, Immediate,  2);
            Op("ORA", 0x0D, ORA, Absolute,   4);
            Op("ORA", 0x11, ORA, IndirectY,  5, pageBoundary: true);
            Op("ORA", 0x15, ORA, ZeroPageX,  4);
            Op("ORA", 0x19, ORA, AbsoluteY,  4, pageBoundary: true);
            Op("ORA", 0x1D, ORA, AbsoluteX,  4, pageBoundary: true);
            Op("AND", 0x21, AND, IndirectX,  6);
            Op("AND", 0x25, AND, ZeroPage,   3);
            Op("AND", 0x29, AND, Immediate,  2);
            Op("AND", 0x2D, AND, Absolute,   4);
            Op("AND", 0x31, AND, IndirectY,  5, pageBoundary: true);
            Op("AND", 0x35, AND, ZeroPageX,  4);
            Op("AND", 0x39, AND, AbsoluteY,  4, pageBoundary: true);
            Op("AND", 0x3D, AND, AbsoluteX,  4, pageBoundary: true);
            Op("EOR", 0x41, EOR, IndirectX,  6);
            Op("EOR", 0x45, EOR, ZeroPage,   3);
            Op("EOR", 0x49, EOR, Immediate,  2);
            Op("EOR", 0x4D, EOR, Absolute,   4);
            Op("EOR", 0x51, EOR, IndirectY,  5, pageBoundary: true);
            Op("EOR", 0x55, EOR, ZeroPageX,  4);
            Op("EOR", 0x59, EOR, AbsoluteY,  4, pageBoundary: true);
            Op("EOR", 0x5D, EOR, AbsoluteX,  4, pageBoundary: true);
            Op("SBC", 0xE1, SBC, IndirectX,  6);
            Op("SBC", 0xE5, SBC, ZeroPage,   3);
            Op("SBC", 0xE9, SBC, Immediate,  2);
            Op("SBC", 0xEB, SBC, Immediate,  2);
            Op("SBC", 0xED, SBC, Absolute,   4);
            Op("SBC", 0xF1, SBC, IndirectY,  5, pageBoundary: true);
            Op("SBC", 0xF5, SBC, ZeroPageX,  4);
            Op("SBC", 0xF9, SBC, AbsoluteY,  4, pageBoundary: true);
            Op("SBC", 0xFD, SBC, AbsoluteX,  4, pageBoundary: true);
            Op("ADC", 0x61, ADC, IndirectX,  6);
            Op("ADC", 0x65, ADC, ZeroPage,   3);
            Op("ADC", 0x69, ADC, Immediate,  2);
            Op("ADC", 0x6D, ADC, Absolute,   4);
            Op("ADC", 0x71, ADC, IndirectY,  5, pageBoundary: true);
            Op("ADC", 0x75, ADC, ZeroPageX,  4);
            Op("ADC", 0x79, ADC, AbsoluteY,  4, pageBoundary: true);
            Op("ADC", 0x7D, ADC, AbsoluteX,  4, pageBoundary: true);
            Op("BRK", 0x00, BRK, Implicit,   7);
            Op("CMP", 0xC1, CMP, IndirectX,  6);
            Op("CMP", 0xC5, CMP, ZeroPage,   3);
            Op("CMP", 0xC9, CMP, Immediate,  2);
            Op("CMP", 0xCD, CMP, Absolute,   4);
            Op("CMP", 0xD1, CMP, IndirectY,  5, pageBoundary: true);
            Op("CMP", 0xD5, CMP, ZeroPageX,  4);
            Op("CMP", 0xD9, CMP, AbsoluteY,  4, pageBoundary: true);
            Op("CMP", 0xDD, CMP, AbsoluteX,  4, pageBoundary: true);
            Op("CPX", 0xE0, CPX, Immediate,  2);
            Op("CPX", 0xE4, CPX, ZeroPage,   3);
            Op("CPX", 0xEC, CPX, Absolute,   4);
            Op("CPY", 0xC0, CPY, Immediate,  2);
            Op("CPY", 0xC4, CPY, ZeroPage,   3);
            Op("CPY", 0xCC, CPY, Absolute,   4);
            Op("LSR", 0x46, LSR, ZeroPage,   5, rmw: true);
            Op("LSR", 0x4E, LSR, Absolute,   6, rmw: true);
            Op("LSR", 0x56, LSR, ZeroPageX,  6, rmw: true);
            Op("LSR", 0x5E, LSR, AbsoluteX,  7, rmw: true);
            Op("LSR", 0x4A, LSR, Accumulator,2, rmw: true);
            Op("ASL", 0x06, ASL, ZeroPage,   5, rmw: true);
            Op("ASL", 0x0E, ASL, Absolute,   6, rmw: true);
            Op("ASL", 0x16, ASL, ZeroPageX,  6, rmw: true);
            Op("ASL", 0x1E, ASL, AbsoluteX,  7, rmw: true);
            Op("ASL", 0x0A, ASL, Accumulator,2, rmw: true);
            Op("ROR", 0x66, ROR, ZeroPage,   5, rmw: true);
            Op("ROR", 0x6E, ROR, Absolute,   6, rmw: true);
            Op("ROR", 0x76, ROR, ZeroPageX,  6, rmw: true);
            Op("ROR", 0x7E, ROR, AbsoluteX,  7, rmw: true);
            Op("ROR", 0x6A, ROR, Accumulator,2, rmw: true);
            Op("ROL", 0x26, ROL, ZeroPage,   5, rmw: true);
            Op("ROL", 0x2E, ROL, Absolute,   6, rmw: true);
            Op("ROL", 0x36, ROL, ZeroPageX,  6, rmw: true);
            Op("ROL", 0x3E, ROL, AbsoluteX,  7, rmw: true);
            Op("ROL", 0x2A, ROL, Accumulator,2, rmw: true);
            Op("INC", 0xE6, INC, ZeroPage,   5, rmw: true);
            Op("INC", 0xEE, INC, Absolute,   6, rmw: true);
            Op("INC", 0xF6, INC, ZeroPageX,  6, rmw: true);
            Op("INC", 0xFE, INC, AbsoluteX,  7, rmw: true);
            Op("DEC", 0xC6, DEC, ZeroPage,   5, rmw: true);
            Op("DEC", 0xCE, DEC, Absolute,   6, rmw: true);
            Op("DEC", 0xD6, DEC, ZeroPageX,  6, rmw: true);
            Op("DEC", 0xDE, DEC, AbsoluteX,  7, rmw: true);
            Op("SKB", 0x04, SKB, Immediate,  3);
            Op("SKB", 0x44, SKB, Immediate,  3);
            Op("SKB", 0x64, SKB, Immediate,  3);
            Op("SKB", 0x14, SKB, Immediate,  4);
            Op("SKB", 0x34, SKB, Immediate,  4);
            Op("SKB", 0x54, SKB, Immediate,  4);
            Op("SKB", 0x74, SKB, Immediate,  4);
            Op("SKB", 0xD4, SKB, Immediate,  4);
            Op("SKB", 0xF4, SKB, Immediate,  4);
            Op("SKB", 0x80, SKB, Immediate,  2);
            Op("SKB", 0x82, SKB, Immediate,  2);
            Op("SKB", 0x89, SKB, Immediate,  2);
            Op("SKB", 0xC2, SKB, Immediate,  2);
            Op("SKB", 0xE2, SKB, Immediate,  2);
            Op("ANC", 0x0B, ANC, Immediate,  2);
            Op("ANC", 0x2B, ANC, Immediate,  2);
            Op("ALR", 0x4B, ALR, Immediate,  2);
            Op("ARR", 0x6B, ARR, Immediate,  2);
            Op("ATX", 0xAB, ATX, Immediate,  2);
            Op("SLO", 0x03, SLO, IndirectX,  8, rmw: true);
            Op("SLO", 0x07, SLO, ZeroPage,   5, rmw: true);
            Op("SLO", 0x0F, SLO, Absolute,   6, rmw: true);
            Op("SLO", 0x13, SLO, IndirectY,  8, rmw: true);
            Op("SLO", 0x17, SLO, ZeroPageX,  6, rmw: true);
            Op("SLO", 0x1B, SLO, AbsoluteY,  7, rmw: true);
            Op("SLO", 0x1F, SLO, AbsoluteX,  7, rmw: true);
            Op("RLA", 0x23, RLA, IndirectX,  8, rmw: true);
            Op("RLA", 0x27, RLA, ZeroPage,   5, rmw: true);
            Op("RLA", 0x2F, RLA, Absolute,   6, rmw: true);
            Op("RLA", 0x33, RLA, IndirectY,  8, rmw: true);
            Op("RLA", 0x37, RLA, ZeroPageX,  6, rmw: true);
            Op("RLA", 0x3B, RLA, AbsoluteY,  7, rmw: true);
            Op("RLA", 0x3F, RLA, AbsoluteX,  7, rmw: true);
            Op("RRA", 0x63, RRA, IndirectX,  8, rmw: true);
            Op("RRA", 0x67, RRA, ZeroPage,   5, rmw: true);
            Op("RRA", 0x6F, RRA, Absolute,   6, rmw: true);
            Op("RRA", 0x73, RRA, IndirectY,  8, rmw: true);
            Op("RRA", 0x77, RRA, ZeroPageX,  6, rmw: true);
            Op("RRA", 0x7B, RRA, AbsoluteY,  7, rmw: true);
            Op("RRA", 0x7F, RRA, AbsoluteX,  7, rmw: true);
            Op("SRE", 0x43, SRE, IndirectX,  8, rmw: true);
            Op("SRE", 0x47, SRE, ZeroPage,   5, rmw: true);
            Op("SRE", 0x4F, SRE, Absolute,   6, rmw: true);
            Op("SRE", 0x53, SRE, IndirectY,  8, rmw: true);
            Op("SRE", 0x57, SRE, ZeroPageX,  6, rmw: true);
            Op("SRE", 0x5B, SRE, AbsoluteY,  7, rmw: true);
            Op("SRE", 0x5F, SRE, AbsoluteX,  7, rmw: true);
            Op("ISC", 0xE3, ISC, IndirectX,  8);
            Op("ISC", 0xE7, ISC, ZeroPage,   5);
            Op("ISC", 0xEF, ISC, Absolute,   6);
            Op("ISC", 0xF3, ISC, IndirectY,  8);
            Op("ISC", 0xF7, ISC, ZeroPageX,  6);
            Op("ISC", 0xFB, ISC, AbsoluteY,  7);
            Op("ISC", 0xFF, ISC, AbsoluteX,  7);
            Op("DCP", 0xC3, DCP, IndirectX,  8);
            Op("DCP", 0xC7, DCP, ZeroPage,   5);
            Op("DCP", 0xCF, DCP, Absolute,   6);
            Op("DCP", 0xD3, DCP, IndirectY,  8);
            Op("DCP", 0xD7, DCP, ZeroPageX,  6);
            Op("DCP", 0xDB, DCP, AbsoluteY,  7);
            Op("DCP", 0xDF, DCP, AbsoluteX,  7);
            Op("LAX", 0xA3, LAX, IndirectX,  6);
            Op("LAX", 0xA7, LAX, ZeroPage,   3);
            Op("LAX", 0xAF, LAX, Absolute,   4);
            Op("LAX", 0xB3, LAX, IndirectY,  5, pageBoundary: true);
            Op("LAX", 0xB7, LAX, ZeroPageY,  4);
            Op("LAX", 0xBF, LAX, AbsoluteY,  4, pageBoundary: true);
            Op("SAX", 0x83, SAX, IndirectX,  6);
            Op("SAX", 0x87, SAX, ZeroPage,   3);
            Op("SAX", 0x8F, SAX, Absolute,   4);
            Op("SAX", 0x97, SAX, ZeroPageY,  4);
            Op("XAA", 0x8B, XAA, Immediate,  2);
            Op("AXS", 0xCB, AXS, Immediate,  2);
            Op("AHX", 0x93, AHX, IndirectX,  6);
            Op("AHX", 0x9F, AHX, AbsoluteY,  5);
            Op("SHX", 0x9E, SHX, AbsoluteY,  5);
            Op("SHY", 0x9C, SHY, Absolute,   5);
            Op("TAS", 0x9B, TAS, AbsoluteY,  5);
            Op("LAS", 0xBB, LAS, AbsoluteY,  4);
            Op("KIL", 0x02, KIL, Implicit,   0);
            Op("KIL", 0x22, KIL, Implicit,   0);
            Op("KIL", 0x42, KIL, Implicit,   0);
            Op("KIL", 0x62, KIL, Implicit,   0);
            Op("KIL", 0x12, KIL, Implicit,   0);
            Op("KIL", 0x32, KIL, Implicit,   0);
            Op("KIL", 0x52, KIL, Implicit,   0);
            Op("KIL", 0x72, KIL, Implicit,   0);
            Op("KIL", 0x92, KIL, Implicit,   0);
            Op("KIL", 0xB2, KIL, Implicit,   0);
            Op("KIL", 0xD2, KIL, Implicit,   0);
            Op("KIL", 0xF2, KIL, Implicit,   0);

        }
    }
}
